### ISSUE TITLE
MELPA integration?

### ISSUE THREAD

**Issue by rphillips** [keith/evil-tmux-navigator#1]
any chance we could get this into melpa?

**Comment by keith** [comment]
I submitted a PR for this, please comment if I did something wrong! https://github.com/milkypostman/melpa/pull/2527

**Comment by rphillips** [comment]
sweet. thanks!

**Comment by keith** [comment]
As you can see from the linked issue (which I have closed), submitting to melpa requires pretty massive changes to how this works. If you can provide those changes as a PR without ruining the purpose of this plugin, I will gladly accept them and resubmit a pull request.
