### ISSUE TITLE
Add spacemacs installation instructions

### ISSUE THREAD

**Issue by jamesla** [keith/evil-tmux-navigator#3]
Just letting you know that this page links to you - http://spacemacs.org/layers/+tools/tmux/README.html to find out how to configure your plugin for spacemacs - however following your instructions don't work for (for spacemacs).

Is there any further instructions to get your plugin working in spacemacs?

**Comment by keith** [comment]
I haven't used emacs enough to know why the setup for "vanilla" emacs would differ from spacemacs. By don't work do you mean that after requiring the package successfully the keybindings still don't work?

**Comment by tthew** [comment]
This appears to be an issue with Spacemacs / the spacemacs tmux layer; https://github.com/syl20bnr/spacemacs/issues/5975

**Comment by keith** [comment]
Thanks for figuring this out. Feel free to open a PR or issue if we need to add anything in the future!
