### ISSUE TITLE
Please add movement between emacs' own windows

### ISSUE THREAD

**Issue by viccuad** [keith/evil-tmux-navigator#4]
Hi,
It would be awesome to use evil-tmux-navigator to navigate seamlessly between
emacs' own windows (apart from tmux panes), as christoomey/vim-tmux-navigator does.

Cheers and thanks

**Comment by keith** [comment]
That should be working already? See https://github.com/keith/evil-tmux-navigator/blob/master/navigate.el#L36

**Comment by wadkar** [comment]
Do I need to `(require 'navigate)` in my `~/.spacemacs` file for this to work?

**Comment by keith** [comment]
@wadkar yes
